# Examples of how to specifically exclude certain things
AllCops:
  Exclude:
    - '**/*.yml'
    - '**/*.sql'
    - 'config/**/*'
    - !ruby/regexp /old_and_unused\.rb$/

# Disable cops for styles that we do not adhere to or are not agreed upon
Style/Documentation:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false
Lint/EmptyInterpolation:
  Enabled: false
Metrics/LineLength:
  Enabled: false
Style/SingleSpaceBeforeFirstArg:
  Enabled: false
Style/StringLiterals:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/SignalException:
  Enabled: false

# Set configuration options for certain cops
Style/AndOr:
  EnforcedStyle: conditionals
